# 服务器配置
server:
  host: "0.0.0.0"          # 服务器主机
  port: 3250               # 服务器端口
  mode: "debug"            # 运行模式: debug, release, test


# 数据库配置
database:
  path: "./data/game.db"   # BoltDB文件路径
  timeout: 5               # 操作超时(秒)

# AI配置
ai:
  default_model: "gemini-2.5-pro"    # 默认AI模型
  max_concurrent: 10        # 最大并发请求数
  timeout: 30              # 请求超时(秒)
  default_think_time: 0    # 默认思考时间(秒)
  default_temperature: 0.7 # 默认创造性参数
  max_tokens: 4000        # 最大token数
  # 新增AI API配置
  api_url: "https://generativelanguage.googleapis.com/v1beta/models"  # AI API地址
  api_key: ""                            # API密钥
  provider: "gemini"                                      # AI服务提供商

# 日志配置
log:
  level: "debug"           # 日志级别: debug, info, warn, error
  file_path: "./logs/app.log"  # 日志文件路径
  max_size: 100           # 最大文件大小(MB)
  max_age: 30             # 最大保存天数
  compress: true          # 是否压缩

# 游戏配置
game:
  default_room_capacity: 3      # 默认房间容量
  default_game_timeout: 1800    # 默认游戏超时(秒)
  default_bidding_timeout: 30   # 默认叫地主超时(秒)
  default_play_timeout: 60      # 默认出牌超时(秒)
  max_rooms_per_user: 10        # 用户最大房间数
  max_ai_players_per_room: 2    # 房间最大AI玩家数